### ISSUE TITLE
resource://dactyl-content/bookmarks.js: 376: TypeError: window.convertFromUnicode is not a function

### ISSUE THREAD

**Issue by sanjayankur31** [5digits/dactyl#201]
Hiya,

I get this error when I add new keyword searchs and attempt to use them via pentadactyl:

```
resource://dactyl-content/bookmarks.js: 376: TypeError: window.convertFromUnicode is not a function
```

I've tested it with a new keyword search for GitHub and Google Scholar, and I get the same error both times.

How to reproduce:
------------------------

- Go to Github
- Right click on top search box
- Click "Add keyword for this search"
- Add a keyword, for example, `github-search`
- Once added, press `t` (for new tab)
- Type in `github-search` followed by a search term

It errors. Same process with Google-Scholar too.

I'm not sure if this is a dactyl or a FF error. i've only noticed it breaking recently. I see quite a few posts regarding errors with keyword search, so it could be an FF error.

**Comment by sanjayankur31** [comment]
A workaround seems to be to manually edit the search link and remove stuff other than the `q=%s` part. So, the github search URL becomes: `https://github.com/search?q=%s`, for example.

**Comment by tim-teufel** [comment]
I also start getting this error with keyword searches after upgrading FF from 50 to 51.

**Comment by mgollo** [comment]
I can confirm tim-teufel's comment: I get this for all searches since the upgrade to FF51
